### ISSUE TITLE
500 entries limitation?

### ISSUE THREAD

**Issue by Heart1010** [danielnagel/fritzbox-blacklist#1]
Thanks for the script (not tested yet) - but StevenBlack/hosts files have >10.000 entries in it - when I read AVM help site correct the FritzBox Blacklist can only handle 500 entries max in his blacklist filter list?

**Comment by danielnagel** [comment]
You're completely right! I code faster then I read the documentary.
I am actually using [Pi Hole](https://pi-hole.net/) right now because of this.
I will mention this issue in the readme.
